### ISSUE TITLE
private_dns folder should be renamed to hostnames

### ISSUE THREAD

**Issue by aouyang1** [InsightDataScience/pegasus#15]
Incorrent naming of private_dns folder. Can be misleading.

**Comment by nguyent** [comment]
Fix for #15
Changed SSH folder name to be case-sensitive
Renamed private_dns folder to hostnames everywhere
README updates

**Comment by nguyent** [comment]
This can be closed

**Comment by aouyang1** [comment]
Yup! gonna check out if everything works fine in the branch and then will merge it back into the master.
