### ISSUE TITLE
Add work-around for VPC hostname issue on Ubuntu 14.04 AMI

### ISSUE THREAD

**Issue by ddrum001** [InsightDataScience/pegasus#26]
While using VPCs within Ubuntu 14.04 AMI on AWS, hosts our unable to resolve their own private DNS.

Need to explicitly add their Private IP and Hostname to the /etc/hosts file on each machine in the cluster.  This can easily be done with cat and ssh.

Should be inserted before running ec2install <cluster> ssh

**Comment by aouyang1** [comment]
Found out that the auto generated VPC and subnets will have a side effect of if the auto-assigned Public IP is not checked when deploying instances, will not allow internal communication between nodes in the subnet. If the auto-assigned Public IP is checked, then internal communication works just fine. 

Using the Insight-internal VPC for some reason does always permite internal communication regardless if I auto-assign Public IPs or not. Not sure if this VPC was generated manually.
