### ISSUE TITLE
Invalid Zookeeper version in download_tech

### ISSUE THREAD

**Issue by abtrout** [InsightDataScience/pegasus#32]
The [Zookeeper version](https://github.com/InsightDataScience/pegasus/blob/master/install/download_tech#L22) specified in `install/download_tech` doesn't exist (yet).

This causes `curl_tech` to fail, and subsequently breaks `ec2install <cluster> zookeeper` attempts.

It [looks like](https://www.apache.org/dist/zookeeper/stable/) the current version of Zookeeper is 3.4.6. Modifying this fixed things for me.

**Comment by aouyang1** [comment]
Thanks for the heads up! I'll get this changed. Let me know if there's any other issues.
