### ISSUE TITLE
Blink DB and Impala Install on AWS

### ISSUE THREAD

**Issue by KalyanaMiriyala** [InsightDataScience/pegasus#34]
Hello David:

Pl. have Blink DB and Impala installed on AWS cluster, for my comparison project.

Thanks
kalyana

**Comment by ddrum001** [comment]
Will work on this tonight!

**Comment by ddrum001** [comment]
Blink is being deprecated (replaced by PartialResult option in Spark) and Impala requires CDH, which is quite involved to integrate into Pegasus.
