### ISSUE TITLE
pegasys does not work with cygwin

### ISSUE THREAD

**Issue by shabss** [InsightDataScience/pegasus#37]
Cygwin running on Windows8 64bit

/usr/local/kafka/conf/server.properties
* broker.id=<public_dns> instead of integer

/var/lib/zookeeper/myid
* cat shows <public_dns> instead of int

(Possibly others, will edit when i find them)

**Comment by aouyang1** [comment]
Thanks for the heads up. Pegasus has only been tested on macs and lightly on ubuntu 14.04. I'll be sure to test this on cygwin as well in the future.
