### ISSUE TITLE
ec2install on kafka does not set JMX_PORT

### ISSUE THREAD

**Issue by shabss** [InsightDataScience/pegasus#38]
I had to manually add JMX_PORT entry (export JMX_PORT=${JMX_PORT:-9999}) in  /usr/local/kafka/bin/kafka-server-start.sh

ec2install run from :
ubuntu@ip-172-31-2-169:~/projects/pegasus$ uname -a
Linux ip-172-31-2-169 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aouyang1** [comment]
Will add this to the config in kafka. Thanks for the find!

**Comment by aouyang1** [comment]
This has been updated in the kafka configs. Kafka-manager installation is on its way as well. Closing for now.
