### ISSUE TITLE
upon installation of (some) packages, pegasus hijacks server-side tmux

### ISSUE THREAD

**Issue by jgors** [InsightDataScience/pegasus#43]
when installing kafka and spark, pegasus starts up a 'kafka_server' tmux session and an 'ipython_notebook' session, respectively; however, if tmux isn't already running on the server, this pegasus spawned tmux server hijacks the user level tmux environment -- meaning, all keybindings are lost, as well as the user level .tmux.conf not being recognized.

**Comment by aouyang1** [comment]
I'm not quite sure I understand the issue. tmux sessions will be opened up on the remote nodes on aws. It should not open any on your local laptop. tmux also should already be running on the remote nodes as long as they are running ubuntu 14.04
