### ISSUE TITLE
assuming ~/.profile by default

### ISSUE THREAD

**Issue by jgors** [InsightDataScience/pegasus#44]
rather than basing everything off of `~/.profile`, perhaps check what shell the user is running (eg. capture ` which $SHELL`) and append to that environment -- eg. I use the zsh and `.profile` is not by default inherited/sourced by the zsh environment, so you could check what the shell environment is upon installation and append to that instead of always using `.profile`.  this took me awhile to figure out why none of the environment variables were there after installation of packages w/ pegasus.  or at least be explicit in the docs that stuff get appended to `.profile` so folks can source that from their actual shell environment.

**Comment by aouyang1** [comment]
That makes sense. I will see if this can be added to future commits. Isn't the default shell in ubuntu14.04 just the basic bash? You would need to install zsh on all the machines right?
