### ISSUE TITLE
MapReduce job tracking via http:// does not work

### ISSUE THREAD

**Issue by jsapan** [InsightDataScience/pegasus#50]
Running jobs yield job tracking URL in form
http://{private hostname}:8088/proxy/application_jobID

Even if the public IP is substituted, the job tracker returns HTTP ERROR 500

Able to reach main interface at http://{public IP}:8088/

[Error 500 output.zip](https://github.com/InsightDataScience/pegasus/files/125551/Error.500.output.zip)

**Comment by aouyang1** [comment]
Have you tried running the following command on your namenode?

$HADOOP_HOME/sbin/mr-jobhistory-daemon.sh start historyserver
