### ISSUE TITLE
zookeeper wont install

### ISSUE THREAD

**Issue by shabss** [InsightDataScience/pegasus#56]
zookeeper is coded as:
ZOOKEEPER_VER = 3.4.6
ZOOKEEPER_URL=http://www.us.apache.org/dist/zookeeper/stable/zookeeper-$ZOOKEEPER_VER.tar.gz

URL has changed to:
ZOOKEEPER_URL=http://www.us.apache.org/dist/zookeeper/stable/zookeeper-3.4.8.tar.gz

I changed the download_tech file to contine

**Comment by aouyang1** [comment]
Thanks for the heads up! Will change this as well
