### ISSUE TITLE
Add start and stop of on_demand instances

### ISSUE THREAD

**Issue by aouyang1** [InsightDataScience/pegasus#65]

**Comment by danielblazevski** [comment]
check if returns spot instances, and do not stop and echo that cannot stop spot instances

**Comment by aouyang1** [comment]
get_instance_ids_with_name_and_role will also fetch instance ids of terminated instances by removing the filter. We need to filter somehow for running and stopped instances

**Comment by aouyang1** [comment]
We should throw a warning that they are stopping instances and confirm that they really want to stop. Similar to peg down
