### ISSUE TITLE
Auto-association of Elastic IPs problematic.

### ISSUE THREAD

**Issue by aaronbinns** [InsightDataScience/pegasus#78]
In our AWS account, we don't have many EIPs available to us -- they are all in use. So, having Pegasus automatically try to associate an EIP to every node in the cluster doesn't work. 

For example, we may only have 5 EIPs available and we want a 20-node spark cluster.  The way the Pegasus code is currently written, it tries to associate an EIP to each node and as soon as we run out of EIPs, we get errors.

As a quick hack, I wrapped that section in code with a check for an environment variable being defined named AWS_ELASTIC_IPS. If it's defined, then it will run the EIP association code, otherwise it will skip it.

Pull request: https://github.com/InsightDataScience/pegasus/pull/77

**Comment by aouyang1** [comment]
We've now added a separate field in the instance template `use_eips` which can be set to true or false. This is read in as an environment variable and used at the stage where eips are potentially created. Closing now
