### ISSUE TITLE
Kibana is installed on the entire ES cluster. Installation on just one of the nodes in the cluster should be fine.

### ISSUE THREAD

**Issue by ronaknnathani** [InsightDataScience/pegasus#88]

**Comment by aouyang1** [comment]
Yup thanks for the heads up. I'm working on the flink branch that is also taking the service part out of the installation.

**Comment by ronaknnathani** [comment]
I am working on a branch as well where I took out the service part and am fixing ES installation to have marvel agent installed and also specify minimum number of masters

**Comment by aouyang1** [comment]
Gotcha. We'll fix the merge conflict when it comes. Should be just cutting one line out of the peg install section of peg.sh and stopping the peg service for zeppelin.

**Comment by ronaknnathani** [comment]
Yep. Sounds good!
