### ISSUE TITLE
Permission denied for no reason

### ISSUE THREAD

**Issue by LouisChang** [InsightDataScience/pegasus#89]
My Pegasus worked super fine yesterday and today morning but I just cannot use it right now.

I do not change anything in my pegasus and it just shows 
Permission denied (publicly).
The command I try to use is peg service Sidi-data hadoop stop.

**Comment by ddrum001** [comment]
Sidi, this looks like an issue with AWS rather than Pegasus.  You should check your cluster on the AWS console and see if you can ssh into the node without Pegasus.

**Comment by LouisChang** [comment]
Hello David:

I can use peg ssh xxx well and ssh works too!

I did all the steps I need manually today for HDFS and re-scp my pem key.
But it did not work too.

No idea what happened!

On Wednesday, June 22, 2016, David E Drummond <notifications@github.com>
wrote:

> Sidi, this looks like an issue with AWS rather than Pegasus. You should
> check your cluster on the AWS console and see if you can ssh into the node
> without Pegasus.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/InsightDataScience/pegasus/issues/89#issuecomment-227643511>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEExOm203-A7-AvKewYEUj4850V7cTCQks5qOMBfgaJpZM4I7U6U>
> .
>


-- 
Sidi CHANG
Master in Computer Science (Computational Operations Research Track)
College of William and Mary
Williamsburg, VA, United States

**Comment by ronaknnathani** [comment]
@LouisChang try doing `peg fetch <cluster-name>` once and then try your command. If that doesn't work , try doing `chmod 0400 $PEGASUS_HOME/tmp/<cluster-name>/<pem-key>` and try your command.

**Comment by LouisChang** [comment]
Hi,

I tried and it still seems not working. Last night, I cannot access my worker node by Peg, today I can access my Worker node but not my Master node.
