### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by drfloob** [InsightDataScience/pegasus#97]
In the spirit of the tools that Pegasus deploys, I suggest the Apache 2.0 License. http://choosealicense.com/licenses/apache-2.0/

See http://choosealicense.com/no-license/ for motivation. tl;dr: lack of a license might keep people from using this tool, who would otherwise like to.

**Comment by aouyang1** [comment]
@drfloob Thanks for the tip! We'll try to get this included asap.

**Comment by aouyang1** [comment]
We got the license added! closing this issue
