### ISSUE TITLE
Extra space after vals draws error

### ISSUE THREAD

**Issue by emhoa** [InsightDataScience/pegasus#98]
A single white space after a value will draw an error. e.g., security_group_ids: sg-05a91e7e , will draw an exception even if there is a single trailing white space after the second 'e'.

**Comment by aouyang1** [comment]
@emhoa Yup just tested for it! I'm adding a change to the parse_yaml in the util.sh to accomodate for this. If your template has any white spaces, they will automatically be removed when read in by pegasus. 

Currently working on the memsql branch and will have that feature soon!

**Comment by aouyang1** [comment]
@emhoa fix is in the memsql pull request if you want to check it out.

**Comment by emhoa** [comment]
hey @aouyang1 it does work! only thing that it fails on -- that I was able to catch -- was the extra trailing space on the purchase_type field. it fails on that

**Comment by aouyang1** [comment]
@emhoa Yikes ok. I'm going to test this as well. Thanks for checking up on this.

**Comment by aouyang1** [comment]
Hmm just checked it and I see it removing trailing white spaces on purchase_type. What's the error you are getting or what is the template file you are using?

**Comment by emhoa** [comment]
hey austin, i'll try to see if i can do more testing but when i put an extra space in the purchase_type value of 'on_demand ' on the master template, the error that gets returned is "must specify spot or on_demand for purchase_type"

**Comment by aouyang1** [comment]
@emhoa Oh also this is only on the memsql branch. Haven't merged these changes into master yet.

**Comment by emhoa** [comment]
hey @aouyang1 you were right...I was on the wrong branch. I tested on_demand and it works but there's something funky about spot right now that the creation stage hangs with or without the space so it's likely an aws thing. once that's resolved, i'll be sure to test it again. thanks for fixing that!

**Comment by aouyang1** [comment]
@emhoa Hmm ok. I will check it out as well. I know lately spot prices have been really bad, so pegasus may be waiting forever for the spot request to be fulfilled. every few seconds or so, pegasus pings aws for the spot request ids to see if they are fulfilled.

**Comment by aouyang1** [comment]
@emhoa This issue looks resolved so far. If you find that the spot pricing is bringing up issues, we can open a separate one. Closing for now.
